<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [10]:
import pandas_datareader as pdr
import matplotlib.pyplot as plt
import pandas as pd
import datetime as dt

In [17]:
start = dt.datetime(2005, 1, 1)
end = dt.datetime(2020, 5, 28)
df = pdr.data.DataReader('tipsho40', 'eurostat', start, end)
df.head()

UNIT        Quarterly index                                          \
GEO                 Austria   Belgium  Bulgaria    Cyprus   Czechia
FREQ              Quarterly Quarterly Quarterly Quarterly Quarterly
TIME_PERIOD
2005-01-01              NaN     69.68     76.01     93.41       NaN
2005-04-01              NaN     71.24     79.26     95.38       NaN
2005-07-01              NaN     73.78     81.55     98.79       NaN
2005-10-01              NaN     75.24     83.52    100.64       NaN
2006-01-01              NaN     76.70     87.47    103.04       NaN

UNIT                                                                    \
GEO         Germany (until 1990 former territory of the FRG)   Denmark
FREQ                                               Quarterly Quarterly
TIME_PERIOD
2005-01-01                                              84.2     75.49
2005-04-01                                              82.7     79.46
2005-07-01                                              84.4     85.56
2005-10-01                                              82.0     91.19
2006-01-01                                              83.2     97.68

UNIT                                       ... Quarterly rate of change  \
GEO           Estonia    Greece     Spain  ...                   Latvia
FREQ        Quarterly Quarterly Quarterly  ...                Quarterly
TIME_PERIOD                                ...
2005-01-01      50.59       NaN       NaN  ...                      NaN
2005-04-01      57.07       NaN       NaN  ...                      NaN
2005-07-01      60.25       NaN       NaN  ...                      NaN
2005-10-01      68.14       NaN     123.7  ...                      NaN
2006-01-01      77.03       NaN     128.3  ...                      NaN

UNIT                                                                       \
GEO             Malta Netherlands    Poland  Portugal   Romania    Sweden
FREQ        Quarterly   Quarterly Quarterly Quarterly Quarterly Quarterly
TIME_PERIOD
2005-01-01        NaN         NaN       NaN       NaN       NaN       NaN
2005-04-01       -0.3         1.1      -0.9       NaN       NaN       3.3
2005-07-01        8.3         1.3       0.0       NaN       NaN       3.9
2005-10-01       -2.8         0.5       5.9       NaN       NaN       2.6
2006-01-01        4.9         1.1       4.3       NaN       NaN       3.5

UNIT
GEO          Slovenia  Slovakia United Kingdom
FREQ        Quarterly Quarterly      Quarterly
TIME_PERIOD
2005-01-01        NaN       NaN            NaN
2005-04-01        NaN       NaN            2.9
2005-07-01        NaN       NaN            2.4
2005-10-01        NaN       NaN            0.2
2006-01-01        NaN       NaN            0.6

[5 rows x 84 columns]

In [18]:
list(df)

[('Quarterly index', 'Austria', 'Quarterly'),
 ('Quarterly index', 'Belgium', 'Quarterly'),
 ('Quarterly index', 'Bulgaria', 'Quarterly'),
 ('Quarterly index', 'Cyprus', 'Quarterly'),
 ('Quarterly index', 'Czechia', 'Quarterly'),
 ('Quarterly index',
  'Germany (until 1990 former territory of the FRG)',
  'Quarterly'),
 ('Quarterly index', 'Denmark', 'Quarterly'),
 ('Quarterly index', 'Estonia', 'Quarterly'),
 ('Quarterly index', 'Greece', 'Quarterly'),
 ('Quarterly index', 'Spain', 'Quarterly'),
 ('Quarterly index', 'Finland', 'Quarterly'),
 ('Quarterly index', 'France', 'Quarterly'),
 ('Quarterly index', 'Croatia', 'Quarterly'),
 ('Quarterly index', 'Hungary', 'Quarterly'),
 ('Quarterly index', 'Ireland', 'Quarterly'),
 ('Quarterly index', 'Italy', 'Quarterly'),
 ('Quarterly index', 'Lithuania', 'Quarterly'),
 ('Quarterly index', 'Luxembourg', 'Quarterly'),
 ('Quarterly index', 'Latvia', 'Quarterly'),
 ('Quarterly index', 'Malta', 'Quarterly'),
 ('Quarterly index', 'Netherlands', 'Quarterly'),
 ('Quarterly index', 'Poland', 'Quarterly'),
 ('Quarterly index', 'Portugal', 'Quarterly'),
 ('Quarterly index', 'Romania', 'Quarterly'),
 ('Quarterly index', 'Sweden', 'Quarterly'),
 ('Quarterly index', 'Slovenia', 'Quarterly'),
 ('Quarterly index', 'Slovakia', 'Quarterly'),
 ('Quarterly index', 'United Kingdom', 'Quarterly'),
 ('Annual rate of change', 'Austria', 'Quarterly'),
 ('Annual rate of change', 'Belgium', 'Quarterly'),
 ('Annual rate of change', 'Bulgaria', 'Quarterly'),
 ('Annual rate of change', 'Cyprus', 'Quarterly'),
 ('Annual rate of change', 'Czechia', 'Quarterly'),
 ('Annual rate of change',
  'Germany (until 1990 former territory of the FRG)',
  'Quarterly'),
 ('Annual rate of change', 'Denmark', 'Quarterly'),
 ('Annual rate of change', 'Estonia', 'Quarterly'),
 ('Annual rate of change', 'Greece', 'Quarterly'),
 ('Annual rate of change', 'Spain', 'Quarterly'),
 ('Annual rate of change', 'Finland', 'Quarterly'),
 ('Annual rate of change', 'France', 'Quarterly'),
 ('Annual rate of change', 'Croatia', 'Quarterly'),
 ('Annual rate of change', 'Hungary', 'Quarterly'),
 ('Annual rate of change', 'Ireland', 'Quarterly'),
 ('Annual rate of change', 'Italy', 'Quarterly'),
 ('Annual rate of change', 'Lithuania', 'Quarterly'),
 ('Annual rate of change', 'Luxembourg', 'Quarterly'),
 ('Annual rate of change', 'Latvia', 'Quarterly'),
 ('Annual rate of change', 'Malta', 'Quarterly'),
 ('Annual rate of change', 'Netherlands', 'Quarterly'),
 ('Annual rate of change', 'Poland', 'Quarterly'),
 ('Annual rate of change', 'Portugal', 'Quarterly'),
 ('Annual rate of change', 'Romania', 'Quarterly'),
 ('Annual rate of change', 'Sweden', 'Quarterly'),
 ('Annual rate of change', 'Slovenia', 'Quarterly'),
 ('Annual rate of change', 'Slovakia', 'Quarterly'),
 ('Annual rate of change', 'United Kingdom', 'Quarterly'),
 ('Quarterly rate of change', 'Austria', 'Quarterly'),
 ('Quarterly rate of change', 'Belgium', 'Quarterly'),
 ('Quarterly rate of change', 'Bulgaria', 'Quarterly'),
 ('Quarterly rate of change', 'Cyprus', 'Quarterly'),
 ('Quarterly rate of change', 'Czechia', 'Quarterly'),
 ('Quarterly rate of change',
  'Germany (until 1990 former territory of the FRG)',
  'Quarterly'),
 ('Quarterly rate of change', 'Denmark', 'Quarterly'),
 ('Quarterly rate of change', 'Estonia', 'Quarterly'),
 ('Quarterly rate of change', 'Greece', 'Quarterly'),
 ('Quarterly rate of change', 'Spain', 'Quarterly'),
 ('Quarterly rate of change', 'Finland', 'Quarterly'),
 ('Quarterly rate of change', 'France', 'Quarterly'),
 ('Quarterly rate of change', 'Croatia', 'Quarterly'),
 ('Quarterly rate of change', 'Hungary', 'Quarterly'),
 ('Quarterly rate of change', 'Ireland', 'Quarterly'),
 ('Quarterly rate of change', 'Italy', 'Quarterly'),
 ('Quarterly rate of change', 'Lithuania', 'Quarterly'),
 ('Quarterly rate of change', 'Luxembourg', 'Quarterly'),
 ('Quarterly rate of change', 'Latvia', 'Quarterly'),
 ('Quarterly rate of change', 'Malta', 'Quarterly'),
 ('Quarterly rate of change', 'Netherlands', 'Quarterly'),
 ('Quarterly rate of change', 'Poland', 'Quarterly'),
 ('Quarterly rate of change', 'Portugal', 'Quarterly'),
 ('Quarterly rate of change', 'Romania', 'Quarterly'),
 ('Quarterly rate of change', 'Sweden', 'Quarterly'),
 ('Quarterly rate of change', 'Slovenia', 'Quarterly'),
 ('Quarterly rate of change', 'Slovakia', 'Quarterly'),
 ('Quarterly rate of change', 'United Kingdom', 'Quarterly')]

In [19]:
df.columns

MultiIndex([(         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (         'Quarterly index', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            (   'Annual rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...),
            ('Quarterly rate of change', ...)],
           names=['UNIT', 'GEO', 'FREQ'])

In [20]:
arrays = [[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']]
pd.MultiIndex.from_arrays(arrays, names=('number', 'color'))

MultiIndex([(1,  'red'),
            (1, 'blue'),
            (2,  'red'),
            (2, 'blue')],
           names=['number', 'color'])